apiVersion: v1
kind: ConfigMap
metadata:
  name: joopang-shared-config
  namespace: joopang
data:
  SPRING_PROFILES_ACTIVE: "stage"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  KAFKA_BOOTSTRAP_SERVERS: "kafka.kafka.svc.cluster.local:9092"
  ORDER_SERVICE_URI: "http://order-service:8083"
  COUPON_SERVICE_URI: "http://coupon-service:8082"
  GATEWAY_ALLOWED_ORIGINS: "http://localhost:3000"
  MANAGEMENT_ENDPOINT_HEALTH_PROBES_ENABLED: "true"
  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "health,info,metrics,prometheus"
  MANAGEMENT_ENDPOINT_HEALTH_SHOWDETAILS: "always"
