apiVersion: v1
kind: Secret
metadata:
  name: coupon-mysql-secret
  namespace: joopang
type: Opaque
stringData:
  mysql-root-password: rootpassword
  mysql-username: coupon_user
  mysql-password: coupon_pass
