apiVersion: v1
kind: Secret
metadata:
  name: order-mysql-secret
  namespace: joopang
type: Opaque
stringData:
  mysql-root-password: rootpassword
  mysql-username: order_user
  mysql-password: order_pass
