apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: joopang-vs
  namespace: joopang
spec:
  hosts:
    - "joopang.local"
  gateways:
    - joopang-gateway
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: gateway-service.joopang.svc.cluster.local
            port:
              number: 8080
          weight: 100
